praxis/index.html
=> adjuntar input

profiles/sergioJaramillo.md
=> Feature perfil sergio

profiles/marcoJefferson.md
[//]: Cree y edite archivo con mi nombre
=> create my profile

profiles/danielaTorres.md
###Se agrega perfil de estudiante Daniela Torres
=> Agregar perfil de estudiante de Daniela Torres

profiles/valentinaParedes.md
Se agrega el perfil de la estudiante Valentina Paredes
=> Create my student profile

profiles/juanAlbites.md
=> agregando perfil juanAlbites

profiles/danielQuispe.md
=> create new student profile

profiles/jonathanValencia.md
=> agrega perfil de Jonathan Valencia

praxis/index.html, praxis/juanAlbites.js
=> agregar archivo juanAlbites.js y modificacion en index.html

profiles/edinaelSanguino.md
=> Agregando perfil edinael

profiles/cristhianCepeda.md
Se agregó el perfil de Cristhian en formato MD
=> Agregar perfil de Cristhian Cepeda

praxis/edinaelSanguino.js
=> Agregando script edinael

praxis/cristhianCepeda.js
Este script es una función que recibe un array de estudiantes, organiza la lista en orden aleatorio e imprime parejas. Si el número de estudiantes es impar, imprime un grupo de 3 con los últimos estudiantes.
=> Crear script para organizar parejas de estudiantes

praxis/danielaTorres.js
=> Agregar script Daniela Torres

profiles/andresZuniga.md
=> Feature perfil andres zuniga

praxis/andersonUribe.js
=> repositorio-script

praxis/danielQuispe.js
=> add function random group

praxis/jeffersonVasquez.js
[//]: script to make randoms groups
=> create script to make randoms groups

praxis/andresZuniga.js
=> Agrega script para emparejar estudiantes

praxis/index.html, praxis/valentinaParedes.js
Se agrega Script y se actualiza el HTML
=> Agregar script y editar HTML

praxis/manuelBojaca.js
###Agregado script crear parejas
Se ha agregado en la carpeta praxis/ el script manuelBojaca.js que crea una lista de parejas a partir de un array de nombres
.
=> Agregar script manuelBojaca.js en praxis/

praxis/jonathanValencia.js
=> Agrega funcionalidad de agrupar por parejas, trabajado con sergio (Y)

praxis/valentinaParedes.js
=> Feedback Feature script valentinap

profiles/andresZuniga.md
=> change the title

praxis/danielQuispe.js
La función del script ya retorna los grupos.
=> update script with return

praxis/johanSora.js
Es la correción del ejercicio de parejas al azar, retorna en un arreglo que contiene las parejas de la forma solicitada
=> Review required js

react/with-redux/package-lock.json, react/with-redux/package.json, react/with-redux/src/App.js, react/with-redux/src/components/Posts.js, react/with-redux/src/store/index.js, react/with-redux/src/store/reducers/Posts.reducer.js
=> Clase de redux-thunk

nodejs/crud/package-lock.json, nodejs/crud/package.json, nodejs/crud/server.js, nodejs/first-steps/index.js, nodejs/first-steps/package-lock.json, nodejs/first-steps/package.json
=> Clases de NodeJs

nodejs/mongoose-MVC/package-lock.json, nodejs/mongoose-MVC/package.json, nodejs/mongoose-MVC/server.js, nodejs/mongoose-MVC/src/db.js, nodejs/mongoose-MVC/src/models/video.js, nodejs/mongoose-MVC/steps.txt
=> Clase de conexión de node con mongo e inicio de MVC

nodejs/mongoose-MVC/server.js, nodejs/mongoose-MVC/src/controllers/video.controller.js, nodejs/mongoose-MVC/src/models/video.model.js, nodejs/mongoose-MVC/src/routes/video.js
=> Clase de CRUD con express y mongoose a mongo

nodejs/validations/package-lock.json, nodejs/validations/package.json, nodejs/validations/server.js, nodejs/validations/src/controllers/user.controller.js, nodejs/validations/src/db.js, nodejs/validations/src/models/user.model.js, nodejs/validations/src/routes/user.js
=> Clase de validaciones con mongoose

nodejs/references/package-lock.json, nodejs/references/package.json, nodejs/references/server.js, nodejs/references/src/controllers/review.controller.js, nodejs/references/src/db.js, react/request-axios/.gitignore, react/request-axios/src/App.js
=> Clase de async await y varaibles de entorno

nodejs/auth-jwt/package-lock.json, nodejs/auth-jwt/package.json, nodejs/auth-jwt/server.js, nodejs/auth-jwt/src/controllers/user.controller.js, nodejs/auth-jwt/src/db.js, nodejs/auth-jwt/src/models/user.model.js, nodejs/auth-jwt/src/routes/user.js, nodejs/auth-jwt/src/utils/auth.js, nodejs/middlewares-cors/package-lock.json, nodejs/middlewares-cors/package.json, nodejs/middlewares-cors/serve.js, nodejs/mongoose-MVC/package-lock.json, nodejs/mongoose-MVC/server.js, nodejs/references/src/controllers/review.controller.js, nodejs/references/src/db.js, nodejs/validations/package.json, nodejs/validations/server.js
=> Clase de swagger y autenticación con jwt

files/backend/package-lock.json, files/backend/package.json, files/backend/src/server.js, files/backend/src/utils/formData.js, files/frontend/src/App.js
=> Clase de subida de imagenes

emails/first-steps/package-lock.json, emails/first-steps/package.json, emails/first-steps/server.js, emails/nodemailer/.env.sample, emails/nodemailer/package-lock.json, emails/nodemailer/package.json, emails/nodemailer/src/controllers/user.controller.js, emails/nodemailer/src/db.js, emails/nodemailer/src/models/user.model.js, emails/nodemailer/src/routes/user.js, emails/nodemailer/src/server.js, emails/nodemailer/src/utils/mailer.js
=> Clases de nodemailer

nodejs/mongo-atlas/package-lock.json, nodejs/mongo-atlas/package.json, nodejs/mongo-atlas/server.js, nodejs/mongo-atlas/src/controllers/video.controller.js, nodejs/mongo-atlas/src/db.js, nodejs/mongo-atlas/src/models/video.model.js, nodejs/mongo-atlas/src/routes/video.js, testing/tasks-be/src/models/user.model.js, testing/tasks-be/src/routes/user.test.js
=> Clases de testing viernes en la mañana y mongo atlas
